"""
Defines constants
"""
MODE_TEXT_TO_IMAGE = 1
MODE_IMAGE_TO_IMAGE = 2
MODE_INPAINTING = 3

THUMBNAIL_IMAGE_EDGE_LENGTH = 256
MAIN_IMAGE_CANVAS_SIZE = 768
VIDEO_GENERATOR_THUMBNAIL_IMAGE_WIDTH = 256
VIDEO_GENERATOR_THUMBNAIL_IMAGE_HEIGHT = 144

TRUE_FALSE_LIST = ["True", "False"]

FACE_MODEL_NAME = "ip-adapter-faceid-plusv2_sd15.bin"

GENERATOR_MODEL_TYPE_LIST = [
    "SD 1.5",
    "SDXL",
    "SD 3",
    "Kandinsky 2.2",
    "Pixart Sigma"
]